#import "./fragments/userParts.gql"

mutation LoginContinued ($code: String!) {
  loginContinued: authenticateWithAuthorizationCode(authorizationCode: $code) {
    accessToken
    expiresIn
    user {
      ...userParts
    }
  }
}
